name: test-pr-merge
on:
  pull_request:
    types: [closed]
jobs:
  delete_tags:
    name: Delete PR tags from Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: dockerhub task
        env:
          BRANCH: ${{ github.head_ref }}
          DOCKER_USER: ${{ secrets.DockerHubUser }}
          DOCKER_PASS: ${{ secrets.DockerHubToken }}
        run: |
        echo hello
