name: test-pr-merge
on:
  pull_request:
    types: [closed]
jobs:
  delete_tags:
    name: Delete PR tags from Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: dockerhub task
        env:
          BRANCH: ${{ github.head_ref }}
          DOCKER_USER: ${{ secrets.DockerHubUser }}
          DOCKER_PASS: ${{ secrets.DockerHubToken }}
        run: |
          BRANCH=$(echo -n ${BRANCH} | tr -c '[:alnum:]._-' '-')
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${DOCKER_USER}'", "password": "'${DOCKER_PASS}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -s -X DELETE -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/varshavs/csi-do-plugin/tags/${BRANCH}/
          images=("${BRANCH}-latest" "${BRANCH}-runtime" "${BRANCH}-tools" "${BRANCH}-tests-1.14" "${BRANCH}-tests-1.15" "${BRANCH}-tests-1.16" "${BRANCH}-builder" "${BRANCH}-builder-pre-1.16")
          for i in $images; do curl -s -X DELETE -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/varshavs/csi-do-plugin/tags/${i}/; done
