name: test-pr-merge
on:
  pull_request:
    types: [closed]
jobs:
  delete_tags:
    name: Delete PR tags from Dockerhub
    runs_on: ubuntu-latest
    steps:
      name: hello world
      run: echo "Hello World"
